name: Build and Test

on:
  workflow_dispatch:

jobs:
  build:
    name: Build and Test on Windows
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Install Visual C++ Redistributable
      run: |
        choco install vcredist2010 -y --x64
        choco install vcredist2012 -y --x64
        choco install vcredist2013 -y --x64
        choco install vcredist2015 -y --x64
        choco install vcredist2017 -y --x64
        choco install vcredist2019 -y --x64
        choco install vcredist2022 -y --x64

    - name: Restore NuGet packages
      run: dotnet restore NINA.sln

    - name: Build main project
      run: dotnet build NINA/NINA.csproj --configuration Debug --no-restore

    - name: Build test project
      run: dotnet build NINA.Test/NINA.Test.csproj --configuration Debug --no-restore

    - name: Debug output directory
      shell: pwsh
      run: |
        Get-ChildItem -Recurse NINA.Test\bin\Debug\

    - name: Run unit tests
      run: dotnet test NINA.Test/NINA.Test.csproj --configuration Debug --no-build -p:PlatformTarget=x64 --logger "trx"
